accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name="accounts"

urlpatterns=[
    path('register/',register ,name="register"),
    path('login/', login_view, name="login"),
    path('profile/', profile, name="profile" ),
    path('logout/', Logout, name="logout"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete')

]

blog/urls.py
from django.urls import path
from .views import *

app_name = "blog"

urlpatterns = [
    path('', home, name="home"),
    path('create/',create_and_edit_blog, name="create_post"),
    path('post/<int:post_id>/', post_detail, name="post_detail"),
    path('edit/<int:post_id>/', create_and_edit_blog, name="edit_post"),
    path('mypost/', my_posts, name="my_posts"),
    path('delete/<int:post_id>/', Delete_post, name="delete_post"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import  dashboard_blog_view, dashboard_user_view, dashboard_home_view, dashboard_profile_view, dashboard_logout,dashboard_create_edit_user, delete_user, dashboard_categories_view, clear_filter_search_category, clear_filter_search_user
from accounts.admin import custom_admin_site
from blog.views import dashboard_create_edit_blog, delete_post, dashboard_create_category, dashboard_delete_category, dashboard_delete_category_view, redirect_to_blogs, clear_filter_search_blog
urlpatterns = [
    path('admin/', custom_admin_site.urls), 
    path('',redirect_to_blogs),
    path('dashboard/',dashboard_home_view, name='custom_admin_dashboard'),
    path('dashboard/blogs/', dashboard_blog_view, name='dashboard_blog'),
    path('dashboard/users/', dashboard_user_view, name='dashboard_user'),
    path('dashboard/categories/', dashboard_categories_view, name='dashboard_categories'),
    path('dashboard/create-category/', dashboard_create_category, name='dashboard_create_category'),
    path('dashboard/delete-category/', dashboard_delete_category_view, name='dashboard_delete_category_view'),
    path('dashboard/delete-category/<int:category_id>/', dashboard_delete_category, name='dashboard_delete_category'),
    path('dashboard/blogs/clear_blog_filter', clear_filter_search_blog, name="clear_filter_search_blog"),
    path('dashboard/categories/clear_category_filter', clear_filter_search_category, name="clear_filter_search_category"),
    path('dashboard/users/clear_user_filter', clear_filter_search_user, name='clear_filter_search_user'),
    path('dashboard/profile/', dashboard_profile_view, name='dashboard_profile'),
    path('dashboard/logout/', dashboard_logout, name='dashboard_logout'),
    path('dashboard/create-user/',dashboard_create_edit_user, name='dashboard_create_user'),
    path('dashboard/create-blog/', dashboard_create_edit_blog, name='dashboard_create_blog'),
    path('dashboard/edit-user/<int:user_id>/', dashboard_create_edit_user, name='edit_user'),
    path('dashboard/delete-user/<int:userid>/', delete_user, name='delete_user'),
    path('dashboard/edit-post/<int:post_id>/', dashboard_create_edit_blog, name='edit_post'),
    path('dashboard/delete-post/<int:postid>/', delete_post, name='delete_post'),
    path('blog/', include("blog.urls", namespace="blog")),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.hashers import check_password

class registrationForm(forms.ModelForm):
    # Common fields
    username = forms.CharField(label="Username", min_length=5, required=True)
    email = forms.EmailField(
        label="Email",
        error_messages={"invalid": "Please enter valid EmailId"},
        required=True
    )

    # Password fields
    current_password = forms.CharField(label="Current Password", widget=forms.PasswordInput, required=False)
    new_password = forms.CharField(label="New Password", widget=forms.PasswordInput, required=False)
    confirm_new_password = forms.CharField(label="Confirm New Password", widget=forms.PasswordInput, required=False)

    class Meta:
        model = User
        fields = ['username', 'email']

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        email = cleaned_data.get('email')

        current_password = cleaned_data.get('current_password')
        new_password = cleaned_data.get('new_password')
        confirm_new_password = cleaned_data.get('confirm_new_password')

        is_editing = self.instance and self.instance.pk is not None

        # Only validate password change if editing and new_password was entered
        if is_editing and (new_password or confirm_new_password):
            if not current_password:
                raise forms.ValidationError("Current password is required to set a new password.")

            if not check_password(current_password, self.instance.password):
                raise forms.ValidationError("Current password is incorrect.")

            if new_password != confirm_new_password:
                raise forms.ValidationError("New password and confirmation do not match.")

        # Username uniqueness
        if username:
            qs = User.objects.filter(username=username)
            if is_editing:
                qs = qs.exclude(pk=self.instance.pk)
            if qs.exists():
                raise forms.ValidationError("Username already exists.")

        # Email uniqueness
        if email:
            qs = User.objects.filter(email=email)
            if is_editing:
                qs = qs.exclude(pk=self.instance.pk)
            if qs.exists():
                raise forms.ValidationError("Email already exists.")

        return cleaned_data
class loginForm(forms.Form):
    username=forms.CharField(label="Username", min_length=5, required=True)
    password=forms.CharField(label="Password", min_length=8, max_length=16)

accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from .forms import registrationForm, loginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from blog.models import Post
from blog.forms import DashboardBlogForm
from blog.models import Category
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
# Create your views here.

#User registration
def register(request):
    if request.user.is_authenticated:
        return redirect('/blog/')
    if request.method=="POST":
        form=registrationForm(request.POST)

        if form.is_valid():
            user=form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            messages.success(request, "User registered successfully")
            return redirect('/accounts/login')
        
        else:
            messages.error(request, "Something went wrong")

    else:
        form=registrationForm()

    return render(request, 'accounts/register.html', {"form":form})

@login_required
def redirect_to_custom_dashboard(request):
    if request.user.is_staff:
        return redirect('/dashboard/')
    else:
        return redirect('/admin/')

class AdminLoginRedirectView(LoginView):
    template_name = 'admin/login.html'  # Use Django’s default admin template
    redirect_authenticated_user = True  # Optional, if user is already logged in

    def get_success_url(self):
        if self.request.user.is_staff:
            return reverse_lazy('dashboard_user') 
        return super().get_success_url()

@staff_member_required
def adminlte_dashboard(request):
    redirect('/accounts/adminlte-dashboard/home')
    return render(request, 'dashboard_base.html')

@staff_member_required
def dashboard_blog_view(request):

    selected_title=request.GET.get('title','').strip()
    selected_category=request.GET.get('category','')
    blog_qs=Post.objects.all()

    if selected_title and selected_category:
        blog_qs = Post.objects.filter(title__icontains=selected_title, category__id=selected_category)
        messages.info(request, f"filtered blog by title: {selected_title} and category: {selected_category}")
    elif selected_title:
        blog_qs=Post.objects.filter(title__icontains=selected_title)
        messages.info(request, f"filtered blog by title: {selected_title}")
    elif selected_category:
        blog_qs=Post.objects.filter(category__id=selected_category)
        messages.info(request, f"filtered blog by category: {selected_category}")

    blog=blog_qs.order_by('-created_at')
    paginator=Paginator(blog, 5)
    page_number=request.GET.get('page')
    page=paginator.get_page(page_number)
    blogCount=blog_qs.count()

    form = DashboardBlogForm()
    category_choices = form.fields['category'].queryset
    return render(request, 'dashboard/blog.html', {'blogs':page, 'page_obj':page,'blogCount':blogCount, 'selected_title':selected_title, 'selected_category':selected_category, 'categories': category_choices,})

@staff_member_required
def dashboard_user_view(request):
    selected_username = request.GET.get('username', '').strip()
    selected_email = request.GET.get('email', '').strip()

    if request.user.is_superuser:
        user_qs = User.objects.filter(is_superuser=False)
    elif request.user.is_staff:
         user_qs = User.objects.filter(is_superuser=False, is_staff=False)

    if selected_username:
        user_qs = user_qs.filter(username__icontains=selected_username)
        messages.info(request, f"Filtered user by username: {selected_username}")
    if selected_email:
        user_qs = user_qs.filter(email__icontains=selected_email)
        messages.info(request, f"Filtered user by: {selected_email}")

    users = user_qs.order_by("-date_joined")
    paginator=Paginator(users, 5)
    page_number=request.GET.get('page')
    page=paginator.get_page(page_number)
    usercount=User.objects.all().count()

    return render(request, 'dashboard/user.html', {
        'users': page,
        'page_obj':page,
        'usercount':usercount,
        'selected_username': selected_username,
        'selected_email': selected_email,
    })


@staff_member_required
def dashboard_home_view(request):
    if request.user.is_authenticated:
        user = request.user
        total_blogs = Post.objects.count()
        total_users = User.objects.count()
        context = {
            'user': user,
            'total_blogs': total_blogs,
            'total_users': total_users
        }
        return render(request, 'dashboard/home.html', context)
    return render(request, 'dashboard/home.html')

@staff_member_required
def dashboard_profile_view(request):
    if request.user.is_authenticated:
        user = request.user
        return render(request, 'dashboard/profile.html', {'user': user})
    
#User login
def login_view(request):
    if request.user.is_authenticated:
        return redirect('/blog/')
    
    if request.method=="POST":
        form=loginForm(request.POST)

        if form.is_valid():
            username=form.cleaned_data['username']
            password=form.cleaned_data['password']

            
            user=authenticate(request, username=username, password=password)
            
            if user is not None:
                login(request, user)
                messages.success(request,"User login successfully")
                return redirect('/blog/')
            else:
                messages.error(request, "Invalid user")

           
        
    else:
        form=loginForm()

    return render(request, 'accounts/login.html', {'form': form})

# user profile
@login_required
def profile(request):
    user=request.user
    return render(request, 'accounts/profile.html', {'user':user})

#logout user
@login_required
def Logout(request):
    logout(request)
    messages.success(request, "Logout successfully")
    return redirect('accounts:login')

@staff_member_required
def dashboard_logout(request):
    logout(request)
    messages.success(request, "Logout successfully")
    return redirect('/admin/')

@staff_member_required
def delete_user(request,userid):
    user=User.objects.get(id=userid)
    user.delete()
    messages.success(request, "User deleted successfully")
    return redirect('/dashboard/users')
        
@staff_member_required
def dashboard_categories_view(request):
    form=DashboardBlogForm()
    category = request.GET.get('category')
    authorid = request.GET.get('author')
    print("category:", category)
    print("authordid:", authorid)
    if category and authorid:
        blogs = Post.objects.filter(category=category, author_id=authorid).order_by('-created_at')
        messages.info(request, f"Filtered blogs by category: {category} and author: {authorid}")
    elif category:
        blogs=Post.objects.filter(category=category).order_by('created_at')
        messages.info(request, f"Filtered blogs by category: {category}")
    elif authorid:
        blogs = Post.objects.filter(author_id=authorid).order_by('-created_at')
        messages.info(request, f"Filtered blogs by author: {authorid}")
    elif category is None and authorid is None:
        blogs = Post.objects.all().order_by('-created_at')
    else:
        blogs = Post.objects.all().order_by('-created_at')

    paginator=Paginator(blogs, 5)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    categoryCount=Post.objects.all().count()
    
    categorychoices= Category.objects.values_list('id', 'name')
    authorchoices=form
    return render(request, 'dashboard/categories.html', {'blogs': page_obj,'page_obj':page_obj, 'categoryCount': categoryCount, 'authorchoices': authorchoices,'categorychoices': categorychoices, 'selected_category': category, 'selected_author': authorid})

@staff_member_required
def dashboard_create_edit_user(request, user_id=None):
    user=get_object_or_404(User, id=user_id) if user_id else None

    if request.method=="POST":
        form=registrationForm(request.POST, instance=user)

        if form.is_valid():
            new_user=form.save(commit=False)
            new_password=form.cleaned_data.get('new_password')

            if new_password:
                new_user.set_password(new_password)

            new_user.save()


            if user_id:
                messages.success(request,"User updated successfully")
            else:
                messages.success(request,"User created successfully")
            return redirect('/dashboard/users/')
        else:
            messages.error(request,"Something went wrong")
    else:
        form=registrationForm(instance=user)
    return render(request, 'dashboard/create_edit_user.html', {'form': form, 'user':user})

@staff_member_required
def clear_filter_search_category(request):
    selected_author=request.GET.get('author', '')
    selected_category=request.GET.get('category', '')

    if not selected_category and not selected_author:
        return redirect('/dashboard/categories/')
    try:
        categories=Category.objects.all()
        messages.success(request,"All categories shown successfully")
        return redirect('/dashboard/categories/')
    except Category.DoesNotExist:
        messages.error(request, "No category found")

@staff_member_required
def clear_filter_search_user(request):
    selected_user=request.GET.get('username','').strip()
    selected_email=request.GET.get('email', '').strip()

    if not selected_user and not selected_email:
        return redirect('/dashboard/users/')
    try:
        users=User.objects.all()
        messages.success(request,"All users shown successfully")
        return redirect('/dashboard/users/')
    except User.DoesNotExist:

templates/accounts/login.html
{% extends "layout/layout.html" %}

{% block title %}
   Login
{% endblock %}

{% block content %}
<form method="post" class="container">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_username" class="form-label">Username</label>
        <input type="text" class="form-control" id="id_username" name="username" value="{{ form.username.value|default:'' }}">
        {% if form.username.errors %}
            <div class="text-danger">{{ form.username.errors.0 }}</div>
        {% endif %}
    </div>
    <div class="mb-3">
        <label for="id_password" class="form-label">Password</label>
        <input type="password" class="form-control" id="id_password" name="password">
        {% if form.password.errors %}
            <div class="text-danger">{{ form.password.errors.0 }}</div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
    <a href="/accounts/password_reset" class="card-link">reset Password</a>
</form>
{% endblock  %}

templates/accounts/password_reset.html
{% extends 'layout/layout.html' %}
{% block content %}
<div class="container mt-5">
  <h2>Reset Your Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Send Reset Link</button>
  </form>
</div>
{% endblock %}

templates/accounts/password_reset_complete.html
{% extends 'layout/layout.html' %}
{% block content %}
<div class="container mt-5">
  <h2>Password Reset Successful</h2>
  <p>You can now <a href="/accounts/login">log in</a> with your new password.</p>
</div>
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'layout/layout.html' %}
{% block content %}
<div class="container mt-5">
  <h2>Enter New Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Change Password</button>
  </form>
</div>
{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'layout/layout.html' %}
{% block content %}
<div class="container mt-5">
  <h2>Check Your Email</h2>
  <p>We’ve emailed you instructions to reset your password.</p>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends "layout/layout.html" %}

{% block title %}
   Profile
{% endblock %}

{% block content %}
<div class="card" style="width: 22rem; margin: 0 auto;">
  <div class="card-body">
    <h5 class="card-title">{{ user.username|title }}</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">{{ user.email }}</h6>
    <p class="card-text">
      Member since: {{ user.date_joined|date:"F j, Y" }}<br>
      Last login: {{ user.last_login|date:"F j, Y, g:i a" }}
    </p>
    <a href="{% url 'accounts:logout' %}" class="btn btn-outline-danger">Logout</a>
  </div>
</div>
{% endblock %}

templates/accounts/register.html
{% extends "layout/layout.html" %}

{% block title %}
   Register
{% endblock %}

{% block content %}
<form method="post" class="container">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_username" class="form-label">Username</label>
        <input type="text" class="form-control" id="id_username" name="username" value="{{ form.username.value|default:'' }}">
        {% if form.username.errors %}
            <div class="text-danger">{{ form.username.errors.0 }}</div>
        {% endif %}
    </div>
    <div class="mb-3">
        <label for="id_email" class="form-label">Email address</label>
        <input type="email" class="form-control" id="id_email" name="email" value="{{ form.email.value|default:'' }}">
        {% if form.email.errors %}
            <div class="text-danger">{{ form.email.errors.0 }}</div>
        {% endif %}
    </div>
    <div class="mb-3">
        <label for="id_password" class="form-label">Password</label>
        <input type="password" class="form-control" id="id_password" name="password">
        {% if form.password.errors %}
            <div class="text-danger">{{ form.password.errors.0 }}</div>
        {% endif %}
    </div>
    <div class="mb-3">
        <label for="id_confirmPassword" class="form-label">Confirm Password</label>
        <input type="password" class="form-control" id="id_confirmPassword" name="confirmPassword">
        {% if form.confirmPassword.errors %}
            <div class="text-danger">{{ form.confirmPassword.errors.0 }}</div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Register</button>
    <a href="/accounts/login" class="card-link">Login Here</a>
</form>
{% endblock  %}